// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    double number=0;
		double countAbove=0;
		double countUnder=0;
		int CallMathRandom= Integer.parseInt(args[0]);
		for (int i=0; i<CallMathRandom; i++){
			number= Math.random();
			if (number>0.5) {
				countAbove++;
			}
			else countUnder++;
		}
		
			System.out.println( "> 0.5:  "+ (int) countAbove +" times");
			System.out.println("<= 0.5: "+(int) countUnder+ " times");

			if (countUnder!=0) {
				System.out.println("Ratio:  "+ countAbove/countUnder);
			}
	}
}
